<script lang="ts">
	let openIndex = $state<number | null>(null);

	const FAQ = [
		{
			q: 'How does it work?',
			a: 'Six short texts. Some were written by real humans — famous letters, vintage insults, real books. Some were generated by AI imitating the same style. You tap HUMAN or AI for each one and get the answer instantly. Score out of 6, same puzzle for everyone, new game daily.'
		},
		{
			q: 'Are the "human" texts really human?',
			a: 'Yes — that\'s the whole point. Every human text is verified writing by a real person: historical letters, published books, attested quotes. The reveal tells you exactly who wrote it and when. If we can\'t verify it, it doesn\'t go in the game.'
		},
		{
			q: 'What is Expert mode?',
			a: 'The original game: five AI models answer the same prompt anonymously, and you guess WHICH model wrote each answer. It\'s genuinely hard — and it powers the leaderboard, which tracks how recognizable and how well-liked each model is in blind testing.'
		},
		{
			q: 'Which AI models are included?',
			a: 'Claude (Anthropic), ChatGPT (OpenAI), Gemini (Google), Grok (xAI), and Perplexity. We always use the current flagship version available to standard users. When a major model updates, that\'s a content event — you\'ll see it on the leaderboard.'
		},
		{
			q: 'Are the comparisons fair?',
			a: 'Yes. Every model gets the exact same prompt with identical generation settings and the same length cap. The display order is shuffled per battle — but it\'s the same shuffle for every visitor, so the daily puzzle is shared and scores are comparable.'
		},
		{
			q: 'Are outputs cached?',
			a: 'Yes. Model responses are generated once and stored — every voter sees the same outputs. This keeps costs low (one API call per battle, not per visitor) and makes the vote data comparable across time.'
		},
		{
			q: 'Do I need an account?',
			a: 'No. Your vote history, streak, and player titles are tracked using a random ID stored in your browser. No signup, no email — but your history won\'t carry over to a different device or browser.'
		},
		{
			q: 'Why is 4/5 impossible?',
			a: 'Each model is used exactly once, so if you get four tags right the fifth has nowhere else to go — it must be right too. The possible scores are 0, 1, 2, 3, and 5. Random tagging hits 5/5 about once every 120 tries, and lands on 0/5 more than a third of the time.'
		},
		{
			q: 'How is my streak calculated?',
			a: 'Your streak counts consecutive days on which you played at least one battle. Miss a day and it resets to zero. It\'s tracked locally in your browser.'
		},
		{
			q: 'What do the titles mean?',
			a: 'Your score earns a title: 5/5 is Model Whisperer, 3/5 is Sharp Eye, 2/5 is Decent Read, 1/5 is Mostly Fooled, and 0/5 is Perfectly Fooled — which is more common than you\'d hope.'
		},
		{
			q: 'Why is this better than benchmarks?',
			a: 'Most benchmarks are created or influenced by the AI companies themselves. This is real humans judging real outputs on real tasks — with no model names shown until after you\'ve voted. Brand bias is eliminated by design. The crowd data is what actually happened, not what a lab wanted to publish.'
		},
		{
			q: 'Can I vote on past battles?',
			a: 'Yes. Every battle has a permanent link (shown below the battle card on the homepage). All archived battles are fully voteable and counted in the leaderboard.'
		},
		{
			q: 'How is the data verified — are these real humans or bots?',
			a: 'Each voter gets a random browser fingerprint on first visit (stored in localStorage). One vote per fingerprint per battle. We deduplicate at submission. Coordinated voting is a real risk for any open platform — our mitigation is fingerprint deduplication and we publish raw vote counts so anomalies are visible. Full methodology at /methodology.'
		},
		{
			q: 'Can I access the data for research?',
			a: 'Aggregate results are public on the leaderboard. Individual records are anonymised (no user identity is stored, only fingerprint hashes and vote choices). For bulk exports or research access, contact mark@guessthemodel.com.'
		}
	];

	function toggle(i: number) {
		openIndex = openIndex === i ? null : i;
	}
</script>

<svelte:head>
	<title>FAQ — GuessTheModel</title>
	<meta name="description" content="How does GuessTheModel work? Which AI models are included, how are battles kept fair, and how are player titles earned." />
</svelte:head>

<div class="mx-auto max-w-2xl px-4 sm:px-6 py-10">

	<div class="mb-8">
		<h1 class="text-2xl sm:text-3xl font-bold text-white mb-2">FAQ</h1>
		<p class="text-[#8B949E]">Everything about how GuessTheModel works.</p>
	</div>

	<div class="space-y-2">
		{#each FAQ as item, i}
			<div class="card overflow-hidden">
				<button
					onclick={() => toggle(i)}
					class="w-full flex items-center justify-between px-5 py-4 text-left"
				>
					<span class="text-white font-medium text-sm pr-4">{item.q}</span>
					<span class="text-[#8B949E] text-lg shrink-0 transition-transform duration-200
						{openIndex === i ? 'rotate-45' : ''}">
						+
					</span>
				</button>
				{#if openIndex === i}
					<div class="px-5 pb-5">
						<p class="text-[#8B949E] text-sm leading-relaxed whitespace-pre-line">{item.a}</p>
					</div>
				{/if}
			</div>
		{/each}
	</div>

	<div class="mt-10 text-center">
		<a href="/" class="text-[#6E7681] hover:text-[#8B949E] text-sm transition-colors">
			← Back to battles
		</a>
	</div>

</div>
