-- Migration 006: Human-or-AI decks — the new front-door game
--
-- A deck is a daily set of 6 short texts: some written by real humans
-- (verified public-domain or user-submitted), some generated by AI.
-- Players tap HUMAN or AI per text. The 5-model battle remains as
-- Expert mode.
--
-- Run in the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS decks (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  theme       text NOT NULL,
  -- items: [{ text, source: 'human'|'ai', label, model_id? }, ...]
  -- label: human attribution ("Mark Twain, 1890") or model version label.
  -- Order is fixed at creation (pre-shuffled) — same deck for everyone.
  items       jsonb NOT NULL,
  is_daily    boolean DEFAULT false,
  deck_date   date,
  created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deck_plays (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  deck_id     uuid REFERENCES decks(id) ON DELETE CASCADE NOT NULL,
  -- answers: { "0": "human", "1": "ai", ... } keyed by item index
  answers     jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- set when all items are answered
  score       int,
  fingerprint text NOT NULL,
  created_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS decks_deck_date_idx ON decks(deck_date);
CREATE INDEX IF NOT EXISTS decks_is_daily_idx  ON decks(is_daily) WHERE is_daily = true;

CREATE UNIQUE INDEX IF NOT EXISTS deck_plays_deck_fp_idx ON deck_plays(deck_id, fingerprint);
CREATE INDEX IF NOT EXISTS deck_plays_deck_id_idx ON deck_plays(deck_id);

ALTER TABLE decks      ENABLE ROW LEVEL SECURITY;
ALTER TABLE deck_plays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "decks_public_read"      ON decks      FOR SELECT USING (true);
CREATE POLICY "deck_plays_public_read" ON deck_plays FOR SELECT USING (true);
CREATE POLICY "deck_plays_public_insert" ON deck_plays FOR INSERT WITH CHECK (true);
